title: Gibson Sings on Youtube
description: >- # this means to ignore newlines until "baseurl:"
  A site that lets you search and find a song you may have heard on Youtube being sung by the artist/streamer Gibson. 
baseurl: "" # the subpath of your site, e.g. /blog
domain: gbsn.live
url: "https://gbsn.live" 
twitter_username: danielrouleau
github_username:  danielrouleau

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
